version: "3"
services:
  skistationproject:
    image: azizmk12/skistationrepo:latest
    ports:
      - "5052:8080"
    networks:
      - test123_networkSki

  mysqldb:
    image: mysql:8
    networks:
      - test123_networkSki
    environment:
      - MYSQL_DATABASE=MohamedAzizMakri

networks:
  test123_networkSki:
