version: "3"
services:
  skistationproject:
    image: azer881/skistationimage:skistationimage
    ports:
      - "5051:8080"
    networks:
      - networkSki

    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    networks:
      - networkSki
    environment:
      - MYSQL_DATABASE=AzerLahmarDB

networks:
  networkSki:
