services:


  skistationproject:
    build:
      context: /home/vagrant/Ski-Station-Project
      dockerfile: Dockerfile
    container_name: tpAchat
    image: skistationimage
    restart: always
    ports:
      - "5052:5052"
    depends_on:
      - mysql
    environment:
      - spring.datasource.url=jdbc:mysql://172.22.0.2:3306/MohamedAzizMakri?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRet>      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.datasource.driver-class-name=com.mysql.jdbc.Driver

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=MohamedAzizMakri
    ports:
      - "3307:3306"

networks:
  networkSki:
