version: "3"
services:
  skistationproject:
    image: skistationimage
    ports:
      - "5051:8080"
    networks:
      - networkSki

  mysqldb:
    image: mysql:8
    networks:
      - networkSki
    environment:
      - MYSQL_DATABASE=AzerLahmarDB

networks:
  networkSki:
